/**
 * Weather
 * \"Internal API endpoint for Rumbo to get weather info.\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DayTemperature } from './dayTemperature';

export class Day {
    /**
    * The date for which the daily values are given
    */
    'date'?: string;
    /**
    * The URL for the weather icon to display.
    */
    'iconUrl'?: string;
    /**
    * The Hex code for the weather background colour gradient to display.
    */
    'gradientColor'?: string;
    'temperature'?: DayTemperature;
    /**
    * The percentage chance that it will rain that day
    */
    'chanceOfRain'?: number;
    /**
    * The humidity in the air expressed as a percentage, for the day.
    */
    'humidity'?: number;
    /**
    * The uv factor for the day
    */
    'uv'?: number;
    /**
    * The PM2.5 value for the day that the API request was made
    */
    'airQuality'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "iconUrl",
            "baseName": "iconUrl",
            "type": "string"
        },
        {
            "name": "gradientColor",
            "baseName": "gradientColor",
            "type": "string"
        },
        {
            "name": "temperature",
            "baseName": "temperature",
            "type": "DayTemperature"
        },
        {
            "name": "chanceOfRain",
            "baseName": "chanceOfRain",
            "type": "number"
        },
        {
            "name": "humidity",
            "baseName": "humidity",
            "type": "number"
        },
        {
            "name": "uv",
            "baseName": "uv",
            "type": "number"
        },
        {
            "name": "airQuality",
            "baseName": "airQuality",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Day.attributeTypeMap;
    }
}

