/**
 * Weather
 * \"Internal API endpoint for Rumbo to get weather info.\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Temperature } from './temperature';

export class DayTemperature {
    'minimum'?: Temperature;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "minimum",
            "baseName": "minimum",
            "type": "Temperature"
        }    ];

    static getAttributeTypeMap() {
        return DayTemperature.attributeTypeMap;
    }
}

