/**
 * Weather
 * \"Internal API endpoint for Rumbo to get weather info.\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Temperature } from './temperature';

export class Hourly {
    /**
    * The date and hour for which the forecast data is given. This is given in UTC.
    */
    'datetime'?: string;
    'temperature'?: Temperature;
    /**
    * The URL for the weather icon to display.
    */
    'iconUrl'?: string;
    /**
    * The percentage chance that it will rain that day
    */
    'chanceOfRain'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "datetime",
            "baseName": "datetime",
            "type": "string"
        },
        {
            "name": "temperature",
            "baseName": "temperature",
            "type": "Temperature"
        },
        {
            "name": "iconUrl",
            "baseName": "iconUrl",
            "type": "string"
        },
        {
            "name": "chanceOfRain",
            "baseName": "chanceOfRain",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Hourly.attributeTypeMap;
    }
}

