/**
 * Weather
 * \"Internal API endpoint for Rumbo to get weather info.\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Temperature } from './temperature';

/**
* The weather conditions at the time (or within an hour of) the API call being made
*/
export class Now {
    /**
    * The URL for the weather icon to display.
    */
    'iconUrl'?: string;
    /**
    * The Hex code for the weather background colour gradient to display.
    */
    'gradientColor'?: string;
    'temperature'?: Temperature;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "iconUrl",
            "baseName": "iconUrl",
            "type": "string"
        },
        {
            "name": "gradientColor",
            "baseName": "gradientColor",
            "type": "string"
        },
        {
            "name": "temperature",
            "baseName": "temperature",
            "type": "Temperature"
        }    ];

    static getAttributeTypeMap() {
        return Now.attributeTypeMap;
    }
}

